### ISSUE TITLE
Massive performance issues in Halo 3

### ISSUE THREAD

**Issue by LeRutY** [craftycodie/xenia-canary-netplay#13]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [ ] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Game sometimes takes ages to launch and when it does, it´s running at 0 fps, freezes all the time and audio cuts out. Latest xenia canary works fine with this game https://www.youtube.com/watch?v=qSYSvYN3zvo

Hardware isn´t at fault, GTX 1080, i7 7700K

### Describe what should happen

Normal performance like on xenia canary

**Comment by SarahGreyWolf** [comment]
It's possible the cause is that it's failing to connect to the webserver, the game doesn't really handle that gracefully and just spams requests causing immense slow down due to the fact that requests are currently running synchronously so it basically locks up the game thread
Try deleting the xenia-canary-netplay.config.toml file and letting it regenerate and see if that helps

**Comment by LeRutY** [comment]
> It's possible the cause is that it's failing to connect to the webserver, the game doesn't really handle that gracefully and just spams requests causing immense slow down due to the fact that requests are currently running synchronously so it basically locks up the game thread Try deleting the xenia-canary-netplay.config.toml file and letting it regenerate and see if that helps

Sadly that didn´t help at all. There is at least one guy who´s facing the same issue but we´re in the minority. I haven´t tried Portal 2 yet to see if it behaves similarly
